# Generated by Django 4.0.6 on 2022-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='For_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tovar', models.CharField(max_length=100, verbose_name='Имя товара')),
                ('about_the_tovar', models.TextField(verbose_name='О товаре ')),
                ('articul_tovar', models.CharField(max_length=20, verbose_name='Артикул')),
                ('sostav_tovar', models.CharField(max_length=100, verbose_name='Состав')),
                ('season', models.CharField(choices=[('ЛЕТО', 'ЛЕТО'), ('ЗИМА', 'ЗИМА'), ('ОСЕНЬ', 'ОСЕНЬ'), ('ВЕСНА', 'ВЕСНА')], default='ЛЕТО', max_length=5, verbose_name='Сезон')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
            ],
        ),
    ]
