# Generated by Django 4.0.6 on 2022-11-29 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.CharField(choices=[('РЕБ', 'РЕБЕНОК'), ('МУЖ', 'МУЖЧИНА'), ('ЖЕН', 'ЖЕНЩИНА')], default='МУЖ', max_length=3, verbose_name='Персона')),
                ('category', models.CharField(choices=[('ВСЕ', 'ВСЯ ОДЕЖДА'), ('ВВЕРХ', 'ВЕРХНЯЯ ОДЕЖДА'), ('БРЮКИ', 'БРЮКИ'), ('ДЖИНСЫ', 'ДЖИНСЫ'), ('ФУТБОЛКИ', 'ФУТБОЛКИ'), ('ХУДИ', 'ТОЛСТОВКИ И ХУДИ')], default='ВСЕ', max_length=8, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.AlterModelOptions(
            name='for_man',
            options={'verbose_name': 'Мужчина', 'verbose_name_plural': 'Мужчины'},
        ),
        migrations.AddField(
            model_name='for_man',
            name='image_tovar',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='for_man',
            name='about_the_tovar',
            field=models.CharField(max_length=3000, verbose_name='О товаре '),
        ),
        migrations.AddField(
            model_name='for_man',
            name='double_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_ham.category'),
        ),
    ]
