# Generated by Django 4.0.6 on 2022-11-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0002_category_alter_for_man_options_for_man_image_tovar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='for_man',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
