# Generated by Django 4.0.6 on 2022-11-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0003_alter_category_options_for_man_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tovar', models.CharField(max_length=100, verbose_name='Имя товара')),
                ('about_the_tovar', models.CharField(max_length=3000, verbose_name='О товаре ')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('image_tovar', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('articul_tovar', models.CharField(max_length=20, verbose_name='Артикул')),
                ('sostav_tovar', models.CharField(max_length=100, verbose_name='Состав')),
                ('season', models.CharField(choices=[('ЛЕТО', 'ЛЕТО'), ('ЗИМА', 'ЗИМА'), ('ОСЕНЬ', 'ОСЕНЬ'), ('ВЕСНА', 'ВЕСНА')], default='ЛЕТО', max_length=5, verbose_name='Сезон')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('double_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_ham.category')),
            ],
            options={
                'verbose_name': 'Женщина',
                'verbose_name_plural': 'Женщины',
            },
        ),
    ]
