# Generated by Django 4.0.6 on 2022-12-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0004_for_women'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
    ]
