# Generated by Django 4.0.6 on 2022-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0006_tovars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovars',
            name='accounte',
            field=models.CharField(max_length=50, null=True, verbose_name='login'),
        ),
    ]
