# Generated by Django 4.0.6 on 2022-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0008_tovars_id_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_man',
            name='size',
            field=models.CharField(choices=[('XXS', 'XSS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='Размер'),
        ),
    ]
