# Generated by Django 4.0.6 on 2022-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0009_for_man_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_man',
            name='color',
            field=models.CharField(max_length=100, null=True, verbose_name='Цвет '),
        ),
    ]
