# Generated by Django 4.0.6 on 2022-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0011_corzina_alter_tovars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_man',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет '),
        ),
        migrations.AlterField(
            model_name='for_man',
            name='size',
            field=models.CharField(blank=True, choices=[('XXS', 'XSS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='Размер'),
        ),
    ]
