# Generated by Django 4.0.6 on 2022-12-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0012_alter_for_man_color_alter_for_man_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='corzina',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
