# Generated by Django 4.0.6 on 2022-12-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0013_corzina_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corzina',
            name='count',
            field=models.IntegerField(default=1, null=True, verbose_name='Количество'),
        ),
    ]
