# Generated by Django 4.0.6 on 2022-12-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_women',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет '),
        ),
        migrations.AddField(
            model_name='for_women',
            name='size',
            field=models.CharField(blank=True, choices=[('XXS', 'XSS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='Размер'),
        ),
    ]
