# Generated by Django 4.1.5 on 2023-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ham', '0019_alter_for_women_about_the_tovar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
